[package]
name = "pest_typed_generator"
description = "Pest-typed's code generator."
version = "0.1.0"
edition = "2021"
keywords = ["pest", "generator"]
categories = ["parsing"]
license = "MIT/Apache-2.0"

[features]
std = ["pest/std"]
grammar-extras = ["pest_meta/grammar-extras"]

[dependencies]
pest = { version = ">=2.7.1" }
proc-macro2 = { version = "*" }
pest_meta = { version = ">=2.7.1" }
quote = { version = "*" }
syn = { version = "*" }
