[package]
name = "pest_typed_generator"
description = "Pest-typed's code generator."
version = "0.3.2"
edition = "2021"
documentation = "https://docs.rs/pest_typed_generator"
homepage = "https://github.com/theverydarkness/pest-typed"
keywords = ["pest", "generator"]
categories = ["parsing"]
license = "MIT/Apache-2.0"

[features]
default = ["std"]
std = ["pest/std"]
grammar-extras = ["pest_meta/grammar-extras"]

[dependencies]
pest = { version = ">=2.7.1" }
proc-macro2 = { version = "^1.0.66" }
pest_meta = { version = ">=2.7.1" }
quote = { version = "^1.0.31" }
syn = { version = "^2.0.26" }
