[workspace]
members = ["derive", "generator", "main"]
resolver = "2"
package.readme = "./README.md"
package.version = "0.13.0-alpha2"

[workspace.dependencies]
pest = { version = "2.7.9" }
pest_meta = { version = "2.7.9" }
pest_derive = { version = "2.7.9" }

[workspace.dependencies.pest_typed]
path = "./main"
version = "0.13.0-alpha2"
default-features = false

[workspace.dependencies.pest_typed_generator]
path = "./generator"
version = "0.13.0-alpha2"
default-features = false
