[workspace]
members = ["derive", "generator", "main"]
resolver = "2"
package.readme = "./README.md"
package.version = "0.12.1"

[workspace.dependencies]
pest = { version = "2.7.5" }
pest_meta = { version = "2.7.5" }

[workspace.dependencies.pest_typed]
path = "./main"
version = "0.12.1"
default-features = false

[workspace.dependencies.pest_typed_generator]
path = "./generator"
version = "0.12.1"
default-features = false
