[package]
name = "pest-typed-derive"
description = "pest-typed's derive macro."
version = "0.1.0"
edition = "2021"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
pest-typed-generator = { path = "../generator" }
