[package]
name = "pest_typed_derive"
description = "pest-typed's derive macro."
version = "0.1.9"
edition = "2021"
documentation = "https://docs.rs/pest_typed_derive"
homepage = "https://github.com/theverydarkness/pest-typed"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[features]
std = ["pest_typed/std", "pest_typed_generator/std"]
grammar-extras = ["pest_typed_generator/grammar-extras"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
pest_typed_generator = { path = "../generator", version = "0.1.9" }

[dev-dependencies]
pest_typed = { path = "../main", version = "0.1.9" }
